---
dist: bionic
language: generic

before_install:
  - scripts/travis.sh

env:
  global:
    - REPOSITORY=osism/openstackclient
  matrix:
    - VERSION=latest PYTHON_VERSION=3.7
    - VERSION=rocky PYTHON_VERSION=3.6
    - VERSION=stein PYTHON_VERSION=3.7
    - VERSION=train PYTHON_VERSION=3.7

before_script:
  - bash scripts/lint.sh

script:
  - bash scripts/build.sh

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then bash scripts/push.sh; fi'

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
