---
name: Build container image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - .github/workflows/build-container-image.yml
      - Containerfile
      - files/**
      - scripts/**
  pull_request:
    paths:
      - .github/workflows/build-container-image.yml
      - Containerfile
      - files/**
      - scripts/**

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openstack_version:
          - rocky
          - stein
          - train
          - ussuri
          - victoria
          - wallaby
          - xena
          - yogi
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Setup docker
      #   uses: docker/setup-buildx-action@v1

      - name: Build container image
        run: scripts/scratch.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          VERSION: ${{ matrix.openstack_version }}
          REPOSITORY: osism/openstackclient
